var palavras = [
    [['c','o','r','i','n','t','h','i','a','n','s'],['tristeza']],
    [['h','a','m','i','l','t','o','n'],['Maior']],
    [['j','a','v','a'],['linguagem']],
    [['M', 'a', 'ç', 'ã'], ['Fruta']],
    [['S', 'o', 'l'], ['Astro']],
    [['L', 'i', 'v', 'r', 'o'], ['Leitura']],
    [['G', 'a', 't', 'o'], ['Animal']],
    [['A', 'z', 'u', 'l'], ['Cor']],
    [['P', 'i', 'a', 'n', 'o'], ['Música']],
    [['M', 'o', 'n', 't', 'a', 'n', 'h', 'a'], ['Elevação']],
    [['C', 'a', 'f', 'é'], ['Bebida']],
    [['V', 'o', 'o'], ['Ação']],
    [['A', 'b', 'r', 'a', 'ç', 'o'], ['Carinho']],
    [['R', 'i', 'o'], ['Água']],
    [['I', 'n', 'v', 'e', 'r', 'n', 'o'], ['Estação']],
    [['F', 'a', 'r', 'o', 'l'], ['Luz']],
    [['T', 'r', 'a', 'v', 'e', 's', 's', 'e', 'i', 'r', 'o'], ['Apoio']],
    [['R', 'i', 's', 'o'], ['Alegria']],
    [['C', 'o', 'r', 'r', 'e', 'r'], ['Velocidade']],
    [['J', 'a', 'r', 'd', 'i', 'm'], ['Natureza']],
    [['L', 'u', 'a'], ['Celestial']],
    [['A', 'v', 'e', 'n', 't', 'u', 'r', 'a'], ['Jornada']],
    [['C', 'â', 'm', 'e', 'r', 'a'], ['Fotografia']],
    [['P', 'o', 'e', 's', 'i', 'a'], ['Expressão']],
    [['S', 'u', 's', 'p', 'i', 'r', 'o'], ['Respiração']],
    [['O', 'c', 'e', 'a', 'n', 'o'], ['Mar']],
    [['l','a','n','t','e','r','n','a'], ['Luz']],
    [['D', 'e', 's', 'e', 'j', 'o'], ['Anseio']],
    [['E', 's', 't', 'r', 'e', 'l', 'a'], ['Celestial']],
    [['S', 'o', 'r', 'r', 'i', 's', 'o'], ['Felicidade']],
    [['S', 'i', 'l', 'ê', 'n', 'c', 'i', 'o'], ['Quietude']],
    [['V', 'i', 'a', 'g', 'e', 'm'], ['Jornada']],
    [['G', 'i', 'r', 'a', 's', 's', 'o', 'l'], ['Flor']],
    [['S', 'e', 'r', 'e', 'n', 'i', 'd', 'a', 'd', 'e'], ['Calma']],
    [['A', 'r', 'c', 'o', '-', 'í', 'r', 'i', 's'], ['Cores']],
    [['M', 'e', 'm', 'ó', 'r', 'i', 'a'], ['Lembrança']],
    [['F', 'r', 'a', 'g', 'r', 'â', 'n', 'c', 'i', 'a'], ['Perfume']],
    [['B', 'r', 'i', 's', 'a'], ['Vento']],
    [['E', 's', 'p', 'e', 'r', 'a', 'n', 'ç', 'a'], ['Esperança']],
    [['C', 'a', 'c', 'h', 'o', 'e', 'i', 'r', 'a'], ['Cheiro']],
    [['C', 'a', 's', 't', 'e', 'l', 'o'], ['Fortaleza']],
    [['R', 'a', 's', 'c', 'u', 'n', 'h', 'o'], ['Esboço']],
    [['H', 'o', 'r', 'i', 'z', 'o', 'n', 't', 'e'], ['Vista']],
    [['S', 'a', 'u', 'd', 'a', 'd', 'e'], ['Sentimento']],
    [['C', 'a', 'n', 'ç', 'ã', 'o'], ['Música']],
    [['T', 'e', 'r', 'n', 'u', 'r', 'a'], ['Carinho']],
    [['P', 'e', 'n', 'u', 'm', 'b', 'r', 'a'], ['Sombra']],
    [['I', 'm', 'a', 'g', 'i', 'n', 'a', 'ç', 'ã', 'o'], ['Criatividade']],
    [['A', 'm', 'i', 'z', 'a', 'd', 'e'], ['Relação']],
    [['S', 'o', 'n', 'h', 'o'], ['Sonhar']]
       
]
console.log ( palavras[40][0][6] );
palavras.push([['a','l','e','x',],['nome']])
console.log(palavras)